version: '3.8'

services:
  doc-processor:
    build: .
    volumes:
      - ./docs:/app/docs
      - ./chroma_db:/app/chroma_db
    environment:
      - PYTHONUNBUFFERED=1
    command: ["--help"]  # Mostrar ayuda por defecto, el usuario puede sobrescribir esto
